### ISSUE TITLE
Default value for ['ssh']['allow_tcp_forwarding'] breaks Chef Zero

### ISSUE THREAD

**Issue by pkuczynski** [dev-sec/chef-ssh-hardening#93] opened 2015-06-03 15:42 UTC
The default value for `['ssh']['allow_tcp_forwarding'] = false` breaks Chef with error message:

`ERROR: Net::SSH::Exceptionremote forwarding request failed`

(I am using knife-zero but that should not make a difference here)

**Comment by artem-sidorenko** [comment] 2016-11-08 12:17
@pkuczynski sorry for missing reaction. I'm closing this in order to cleanup the issues a bit. Feel free to reopen if the problem is still present

**Closed by artem-sidorenko** 2016-11-08 12:17 UTC
